server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/A-caro/Send-Mail
          search-paths: config-data

  application:
    name: config-server
